name: push_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  change_app_package_name: ^1.1.0
  equatable: ^2.0.5
  firebase_core: ^2.14.0
  firebase_messaging: ^14.6.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_launcher_icons: ^0.13.1
  flutter_local_notifications: ^14.1.1
  go_router: ^8.0.5

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
